#!/usr/bin/python
#Current complete code as of 6/24/15 9:55 MST



import socket

def raw(msg):
   message = msg+"\r\n"
   irc.send(message.encode())
def chat(msg):
   message = "PRIVMSG #testing123 :" + msg + "\r\n"
   irc.send(message.encode())
def action(msg):
   message = "PRIVMSG #testing123 :\x01ACTION " + msg + "\x01\r\n"
   irc.send(message.encode())
def chatnick(msg):
   nick = data.split()[0]
   message = "PRIVMSG " + nick + ":" + msg + "\r\n"
   irc.send(message.encode())
def auto_op
 


network = 'irc.shaw.ca'
port = 6667
irc = socket.socket( socket.AF_INET, socket.SOCK_STREAM)
irc.connect(( network, port))
 
print(irc.recv(4096).decode())
 
raw('NICK AzothBot')
raw('USER  AzothBot AzothBot AzothBot :Python IRC')
raw('JOIN #testing123')
chat("Hello World")
while True:
   data =(irc.recv(4096).decode()) #removed extra annoying spaces?
   msg = data.split(":")
   if len(msg)> 2:
      # print msg,len(msg)
      who_did = msg[1]
      hostname = who_did.split(" ")[0]
      action = who_did.split(" ")[1]
      nick = hostname.split("!")[0]
      words = msg[2].strip()
 
      print("{} {}: {}".format(nick,action,words))
   else:
      print(msg)
      action = ""

   if data.find('PING') != -1:
      to_send = 'PONG ' + data.split()[1] + "\r\n"  #here, we're storing what you want to send as a variable, we can reference it later?
      irc.send(to_send.encode()) #now, we can send what was stored, with encoding.
   if action == "JOIN": #auto op
      if nick.lower() in auto_op:
         raw("MODE "+ mychan + " +o " + nick)
   if data.find ( '!myBot quit' ) != -1: #quit bot
      chat("Fine, if you don't want me")
      chat('QUIT\r\n')
   if data.find ( '!oldf') !=-1: # makes old fashioned
      action( 'makes an old fashioned for ' + nick)
   if data.find ( '!sandwich') !=-1: #makes sandwich
      action( 'makes a GIGANTIC sanmmich for ' + nick)
   if data.find ( '!hi' ) != -1: #says hi
      chat('Hello')
   if data.find ('!squirrel' ) != -1: #squirrel easter
      chat('WHERE!!!!!!')
   if data.find ('!credits') != -1: #Credits with privat message
      chatnick('-----------------------------------------------------------------------------------')
      chatnick('|Napalm is the creator and the owner of this spectacualr chat                     |')
      chatnick('|fingRfish has a huge roll in this chat from the beginning                        |')
      chatnick('|Without Smack this bot would be homeless                                         |')
      chatnick('|Smack has brought this chat to 1337 status                                       |')
      chatnick('|Thank you Kai, CherylG, missy, and MAP for keeping this chat alive from the start|')
      chatnick('|FingRfish would like to thank his producers, organic                             |')
      chatnick('|elements for making him who he is, rivers which have                             |')
      chatnick('|allowed him to spawn, and the gnomes which                                       |')
      chatnick('|continue to steal his underpants.                                                |')
      chatnick('-----------------------------------------------------------------------------------')
   if data.find ( 'slaps AzothBot' ) != -1:
      chat('This is the Trout Protection Agency. Please put the Trout Down and walk away with your hands in the air.')
   print(data)
